// Constant variables
export const CorporateController = "V_ControllerType";
export const ControllerControlTypes = "ControllerControlTypes";
export const legalStatusController = "v_FirmLegalStatusTypesController";
export const AddressTypesController = "AddressTypes";
export const Title = "TitleTypes";
export const countries = "Countries";
export const qfcLicenseStatus = "v_LicenseStatus";
export const authorisationStatus = "v_AuthorizationStatus";
export const legalStatus = "v_FirmLegalStatusTypes";
export const legalStatusfilter = "LegalStatusTypes";
export const SupervisionCaseOfficer = "V_SupervisionSupervisor";
export const AuthorisationCaseOfficer = "V_AMLSupervisors";
export const FinYearEnd = "FirmFinYearEndTypes";
export const FinAccStd = "FinAccStdTypes";
export const firmAppTypes = "v_FirmApplicationType";
export const addressTypes = "v_EntityAddressTypes";
export const contactAddressTypes = "v_ContactAddressTypes";
export const firmLevels = "UserRoleFirmTypes";
export const prudentialCategoryTypes = "PrudentialCategoryTypes";
export const sectorTypes = "v_SectorTypes";
export const supervisionCategory = "V_SupervisionCategory";
export const authorisationCategoryTypes = "V_AuthorisationCategoryTypes";
export const PLACE_OF_INCORPORATION_QFC = "QFC";
export const firmScopeTypes = "FirmScopeTypes";
export const ControllerType = "V_ControllerType"
export const firmAuditorName = "V_Firm_AuditorName";
export const firmAuditorType = "V_Firm_AuditorType";
export const Regulaters = "V_Regulators";
export const NoticeIssuers = "V_NoticeIssuers";
export const docSubTypes = "DocSubTypes";
export const breachTypes = "BreachTypes";
export const breachCategories = "BreachCategories";
export const breachLevelTypes = "BreachLevelTypes";
export const breachStatusTypes = "BreachStatusTypes";
// Supervision
export const firmRptClassificationTypes = "V_FirmRptClassificationTypes";
export const firmRptClassificationTypesForDNFBPs = "V_FirmRptClassificationTypesForDNFBPs"
export const firmRptBasisTypes = "FirmRptBasisTypes";
// Journal
export const journalEntryTypes = "V_SupervisionJournalEntryTypes";
export const externalAuditors = "V_Firm_AuditorName";
// Reg.Funds
export const TypeOfFund = "V_RegisteredFundTypes";
export const RFFundStatus = "V_RegisteredFundStatusTypes";
// Enf Action
export const enfActionsAuth = "V_EnforcementActionOnTypes_Auth"
export const enfActionsDNFBP = "V_EnforcementActionOnTypes_DNFBP"
export const firmTypes = "V_FirmTypes";
export const firmStatus = "V_FirmStatusTypes";
export const authorisedFirmNames = "V_All_Firms_Authorised";
export const dnfbpsFirmNames = "V_All_Firms_DNFBPs";
// Admin Fee
export const firmRptAdminFeeRates = "V_FirmRptAdminFeeRates";
export const currencyTypes = "V_CurrencyTypes"

// Notices
export const controlledFunctionTypes = "v_ControlledFunctionTypes";
export const contactTypes = "v_ContactTypes";
export const respondentTypes = "V_RespondentTypes";
export const evaluationRequirementType = "V_EvaluationRequirementType";

// Reporting Schedule
export const firmRptSubmissionTypes = "V_FirmRptSubmissionTypes";
export const reportDocTypes = "v_Get_DocType";
export const firmRptNReqReasonTypes = "FirmRptNReqReasonTypes";
export const Q100_PRUDENTIALRETURN = "10";
export const Q200_PRUDENTIALRETURN = "11";
export const Q300_PRUDENTIALRETURN = "12";
export const Q400_PRUDENTIALRETURN = "29";
export const ANNUAL = "Annual";
export const SEMI_ANNUALLY = "Semi-Annual";
export const BI_WEEKLY = "Bi-Weekly";
export const WEEKLY = "Weekly";
export const DAILY = "Daily";
export const OTHER = "Other";
export const QUARTERLY = "Quarterly";
export const BI_ANNUALLY = "Bi-Annually";
export const ANNUALLY = "Annually";
export const MONTHLY = "Monthly";
// top menu
// co-supevisors
export const firmUserAssnTypes = "FirmUserAssnTypes";
export const CoSupervisorsUsers = "V_Users_COSupervisors";
export const firmUserAssnReasonTypes = "FirmUserAssnReasonTypes";
//Query String Parameter for FS Reporting
export const QUERYSTRING_FSRPTDATAID = "fsRptDataID";
export const Specify_Valid_Response = 1200;
export const TEXT_MR = "Mr";
export const TEXT_MS = "Ms";
export const TEXT_MRS = "Mrs";
export const TEXT_DR = "Dr";
export const TEXT_YES = "Yes";
export const TEXT_NOT_APPLICABLE = "Not applicable";
export const TEXT_NO = "No";
export const TEXT_ALL = "All";
export const TEXT_SELECT = "Select";
export const TEXT_ZERO = 0;
export const TEXT_ONE = 1;
export const TEXT_TWO = 2;
export const TEXT_THREE = 3;
export const TEXT_FOUR = 4;
export const TEXT_FIVE = 5;
export const TEXT_SIX = 6;
export const TEXT_SEVEN = 7;
export const TEXT_EIGHT = 8;

export const TEXT_NINE = 9;
export const TEXT_OTHER = "Other";
export const TEXT_OTHER_VALUE = "o";
export const TEXT_MINUS_ONE = -1;
export const TEXT_TRUE = true;
export const TEXT_OTHERS = "Others";

export const TEXT_GRANT = "Grant";
export const TEXT_REVOKE = "Revoke";

export const BLANK_DATE = "__/___/____";
export const DataFieldLabel = "\"##DataFieldLable##\"";
export const ContactTypes = "v_ContactTypes";
export const PreferredMethodofContact = "ContactMethodTypes";

export const BREAK_LINE_TAG = "<br />";
export const HTML_SPACE = "&nbsp;";

export const SLASH_FORWORD = "/";
export const CHAR_SLASH_FORWORD = '/';
export const DOUBLE_FORWORDSLASH = "//";
export const BLANKSPACE = " ";
export const COMMA = ",";
export const AMPERSAND = "&";
export const NEWLINE = "\n";
export const PERCENTAGE = "%";
export const NOT_EQUAL = "!";
export const HASH = "#";
export const DOLLAR_SIGN = "$";
export const OR_SIGN = "|";
export const DOUBLE_BACKSLASH = "\\";
export const QUESTIONMARK = "?";
export const SEMICOLON = ";";
export const SEMICOLON_CHAR = ';';
export const COMMA_CHAR = ',';
export const PERCENTAGE20 = "%20";
export const EQUAL_SIGN = "=";
export const SINGLE_QUOTE = "'";
export const CURLYBRACE_OPEN = "{";
export const CURLYBRACE_CLOSE = "}";
export const BRACKET_OPEN = "(";
export const BRACKET_CLOSE = ")";
export const CHAR_HYPHEN = "-";
export const CHAR_DOT = ".";
export const CHAR_UNDERSCORE = "_";
export const CHAR_AT = "@";
export const CHAR_COLON = ":";
export const CHAR_COLON_WITH_SPACES = " : ";
export const CHAR_MULTIPLY = "*";
export const CHAR_PLUS = "+";
export const CHAR_EQUAL = "=";
export const CHAR_LIKEAPOSTROPHE = "`";
export const CHAR_TILT = "~";
export const CHAR_LESSTHAN = "<";
export const CHAR_GREATERTHAN = ">";
export const CHAR_COMMA = ',';

//Querystrings
export const QUERYSTRING_BREACHID = "bId";
export const QUERYSTRING_BREACHREVISION = "rvNo";
export const QUERYSTRING_FIRMID = "fiD";
export const QUERYSTRING_TABID = "tabId";
export const QUERYSTRING_SCHEDULEITEMID = "rptSchItemID";
export const QUERYSTRING_DOCID = "docID";
export const QUERYSTRING_MSG = "msg";
export const QUERYSTRING_MSG_HEADER = "msgHeader";
export const QUERYSTRING_MSG_DESCRIPTION = "msgDescription";
export const QUERYSTRING_WFSTATUS = "wfStatus";
export const QUERYSTRING_CONTACTID = "cId";
export const QUERYSTRING_CONTACTTYPEID = "ctId";
export const QUERYSTRING_CONTACTSTATUS = "cStatus";
export const QUERYSTRING_OTHERENTITYID = "oeId";
export const QUERYSTRING_RELATEDENTITYID = "reId";
export const QUERYSTRING_RELATEDENTITYTYPEID = "retId";
export const QUERYSTRING_CONTACTASSNID = "caId";
export const QUERYSTRING_FUNCTIONTYPEID = "ftId";

export const QUERYSTRING_AINID = "ainId";
export const QUERYSTRING_APPID = "appId";
export const QUERYSTRING_AINUMBER = "aiNum";
export const QUERTSTRING_FLAG = "flg";
export const QUERYSTRING_INVOICES = "InId";
export const QUERYSTRING_RPTREVIEWID = "rptId";
export const QUERYSTRING_RPTREVISION = "rptRevId";
export const QUERYSTRING_OPERATIONSTATUSID = "operationId";
export const QUERYSTRING_CLIENTCLASSIFICATION = "clientId";
export const QUERYSTRING_INVOICENUMBER = "Inv";
export const QUERYSTRING_FIRMCROWAIVERID = "fcwId";
export const QUERYSTRING_FIRMCROREPORTSCHEDULEID = "fcrsId";
export const QUERYSTRING_PREV_WF_STATUSID = "prevWfSId";
export const QUERYSTRING_LASTDATEOFMONTH = "lDate";
export const QUERYSTRING_AINOCID = "nocID";
export const QUERYSTRING_RSCCID = "rscID";
export const QUERTSTRING_GENSUB = "genID";
export const QUERTSTRING_GENSUBREVNUM = "genRID";
export const QUERYSTRING_ENFID = "enfiD";
export const QUERY_RFID = "rfiD";

// sharePoint Url 
export const sharePointUrl = "https://qfcra365.sharepoint.com/sites/FIRMSUAT/";



export enum FirmLicenseApplStatusType {
    Application = 4,
    Licensed = 5,
    ApplicationWithdrawn = 6,
    Rejected = 7,
    LicensedWithdrawn = 8,
    LicensedWithdrawnInvolunatary = 9
}
export enum FirmAuthorizationApplStatusType {
    Application = 10,
    ApplicationWithdrawn = 11,
    Rejected = 12,
    Authorised = 13,
    AuthorisedWithdrawnVoluntary = 14,
    AuthorisedWithdrawnInvoluntary = 15
}
export enum AuditorsMessages {
    Select_Auditor_Name = 3901,
    Selected_Auditor_Name_already_Exsists = 3903,
    Select_Auditor_Type = 3904,
    Select_Valid_Data_From = 3905,
    Select_Valid_Data_From_Later_Than_To = 3906
}
export enum Firm_CoreDetails_Messages {
    Authorisation = 8500,
    ENTER_LEGAL_STATUS = 8501,
    FIRMDETAILS_SAVED_SUCCESSFULLY = 8502,
    FIRMSAVEERROR = 8503,
    ENTER_FIRMNAME = 8504,
    FIRMEXIST = 8505,
    ENTER_QFCNUMBER = 8506,
    ENTER_NONBLANK_FIRMNAME_AS_IN_FACTSHEET = 8708,
    QFCNUMBEREXISTS = 8507,
    ENTER_VALID_WEBURL = 8508,

    CANNOT_LICENSE_UNTIL_SCOPE_IS_FINALIZED = 8509,
    CANNOT_AUTHORISE_UNTIL_SCOPE_IS_FINALIZED = 8510,
    ENSURE_SCOPE_FINALIZATION_FOR_LICENSE = 8511,
    ENSURE_SCOPE_FINALIZATION_FOR_AUTHORISATION = 8512,
    INVALID_QFCNUMBER = 8513,
    HTTP_APPENDING = 8514,
    ENTER_DATE_OF_APPLICATION = 8515,
    INVALID_DATE_OF_APPLICATION = 8516,
    CANCEL_FIRMDETAILS = 8517,
    ENTER_SUMMARY = 9097,
    SELECT_FIRM = 9098,
    PERSONAL_REMINDER_CREATED = 90100,
    PERSONAL_REMINDER_UPDATED = 90101,
    SELECT_SUPERVISIORS = 9099,
    INCORPORATION_DATE_MSG = 90102,
    INCORPORATION_DATE_MSG_ERROR = 90103,
    TWO_AUTHORISATION_STATUS_ON_SAME_DATE = 90104,
    SAME_AUTHORISATION_STATUS_ON_TWO_DATES = 90105,
    TWO_LICENSED_STATUS_ON_SAME_DATE = 90106,
    SAME_LICENSED_STATUS_ON_TWO_DATES = 90107
}

export enum AddressControlMessages {
    SELECT_ADDRESSTYPE = 2290,
    DUPLICATE_ADDRESSTYPES = 2291,
    ENTER_VALIDPHONENUMBER = 2292,
    ENTER_VALIDFAXNUMBER = 2293,
    ENTERDATE_LESSTHAN_TODAY = 2294
}
export enum ControllerMessages {
    ENTER_ALL_REQUIREDFIELDS = 4000,
    ENTER_VALID_EFFECTIVEDATE = 4001,
    ENTER_OTHER_ENTITY_NAME = 4003,
    ENTER_GREATER_CESSATION_DATE = 4004,
    SELECT_RECORD = 4005,
    RECORD_MODIFIED = 4006,
    RECORD_DELETED = 4007,
    RECORD_INSERTED = 4008,
    NO_RECORD = 4009,
    ENTER_VALID_BIRTHDATE = 4010,
    ENTER_VALID_PERCENTAGE = 4011,
    ENTER_PERCENTAGE_NOTEXCEED = 4012,
    ENTER_FIRSTNAME = 4013,
    ENTER_FAMILYNAME = 4017,
    Select_Place_Establishment = 4016,
    ENTER_REGISTEREDNUMBERCORPORATE = 4014,
    SELECT_TYPEOFCONTROL = 4015,
    SELECT_ISPEP = 9024,
}
export enum ContactMessage {
    FIRMEXIST = 9000,
    NotFound = 9001,
    UnableToSave = 9002,
    ContactFoundMessage = 9003,
    UpdateMessage = 9004,
    SaveContact = 9005,
    SELECTCONTACTTYPE = 9006,
    SELECTENTITYTYPE = 9007,
    INVALIDEMAIL = 9008,
    SAVEERROR = 726,
    MAIN_CONTACT_EXISTS = 9009,
    UPDATECONTACT = 9010,
    ASSOCIATION_CREATED = 9011,
    CONTACT_TYPE_EXISTS = 9012,
    VALIDDATE = 9013,
    EFFECTIVEDATE_AND_ENDDATE = 9014,
    SELECT_ISPEP = 9024,
    //Added By Salim on 02-June-2011
    SelectAvaiContact = 9015,
    CurrentResidenceaddress = 6503,

    //Added by Abrar on 12 sep 2011
    SELECTCONTACT = 9016
}
export enum FirmActivitiesEnum {
    ENTER_ALL_REQUIREDFIELDS = 3000,
    ENTER_VALID_SCOPEEFFECTIVEDATE = 3001,
    CORRECT_PERMITTEDACTIVITIES = 3002,
    ADD_PERMITTEDACTIVITIES = 3003,
    CORRECT_REGULATEDACTIVITIES = 3004,
    ADD_REGULATEDACTIVITIES = 3005,
    SELECT_ACTIVITIES = 3006,
    SELECT_SCOPETYPES = 3007,
    ENTER_VALID_EFFECTIVEDATE = 3008,
    SELECT_ATLEASTONE_PRODUCTS = 3009,
    SELECT_CATEGORY = 3010,
    AREUSURE_CANCELCHANGES = 3011,
    ACTIVITIES_SAVED_SUCCESSFULLY = 3012,
    LICENSED_SCOPE_DELETEDSUCCESSFULLY = 3013,
    AUTHORISED_SCOPE_DELETEDSUCCESSFULLY = 3014,
    DELETEAUTHORISEDSCOPE_BEFORE_LICENSEDSCOPE = 3015,
    DELETE_AIREFERNCEACTIVITY_BEFORE_DELETINGSCOPE = 3016,
    CREATE_LICENSEDSCOPE_BEFORE_AUTORISATIONSCOPE = 3017,
    ACTIVITY_ALREADY_SELECTED = 3018,
    SAVE_LICENSEDSCOPE_BEFORE_AUTORISATIONSCOPE = 3019,
    EXCEPTION_INSERTING_FORMREFERENCE = 3020,
    REVISION_LICENSEDSCOPE = 3021,
    REVISION_AUTHORISEDSCOPE = 3022,
    ENTER_PRUDENTIAL_EFFECTIVEDATE = 3023,
    ENTER_EFFECTIVEDATE_LATER_EARLIEREFFECTIVEDATE = 3024,
    TOCHANGEACTIVITY_DELETEAIREFERENCE = 3025,
    ENTER_VALID_DATE = 3026,
    ENTER_VALID_DATE_FORPRODUCTS = 3027,
    HIT_GETPRODUCTS = 3028,
    ENTER_SECTOR_EFFECTIVEDATE = 3029,
    ENTER_SECTOREFFECTIVEDATE_LATER_EARLIEREFFECTIVEDATE = 3030,
    AUTHORISEDDATEPASSED_CANNOTDESELECTPRODUCT = 3031,
    AISREFERENCE_WITHDRAWNFIRSTBEFORESCOPEWITHDRAWN = 3032,
    ONEORMOREPRODUCTAUTHORISED_CANNOTREMOVE = 3033,
    LICENSEDDATEPASSED_CANNOTREMOVE = 3034,
    WITHDRAWNDATEPASSED_CANNOTREMOVE = 3035,
    ENTER_VALID_APPLICATIONDATE = 3036,
    ENTER_EFFECTIVEDATE_LATER_APPLICATIONDATE = 3037,
    APPLICATIONDATECHANGED_REVISEDSCOPE = 3038,
    SELECT_ISLAMICFINANCE_TYPE = 3039,
    CHANGINGPRUDCAT_RESET_PRUDRETTYPE = 3040,
    SCOPECHANGED_SAVEORREVISE = 3041,
    PRODUCTREFINAIS_CANNOTDESELECT = 3042,
    DELETE_AIREFERNCE_BEFORE_DELETINGSCOPE = 3043,
    APPLICATIONDATE_LATER_COREDETAIL = 3044,
    UNSAVECHANGES_MSG = 3045,
    DATEOFINCORPORATION_ERROR = 3046,
    TREEVEIWMSG = 3047,
    AUTHORISATIONCATEGORYSELECT = 3048,
}

export enum DocumentAttechment {
    SelectDocumentType = 8000,
    saveDocument = 8001,
    selectDocument = 8002,

}

export enum InvoicesMessages {
    INVOICE_AMOUNT = 10500,
    INVOICE_LIST = 10501,
    INVOICE_SELECT = 10502,
    INVOICE_SAVE = 10503,
    INVALID_DATA = 10504,
    INVOICES_SELECT_FRIMS = 10505,
    INVOICES_SELECT_INVOICESFOR = 10506,
    INVOICES_SELECT_NAME = 10507,
    INVOICES_INDIVIDULADATA = 10508,
    INOVICES_EDIT = 10509,
    INVOCIE_OFDATE = 10510,
    INVOICES_PAYMENT = 10511,
    INVOICES_EDITPAGE = 10512,
    INVOICE_DATA_SAVE = 10513,
    INVOICE_DATA_UPDATE = 10514,
    INVOICE_APPLICANTNAME_EXIST = 10515,
    INVOICES_UPDATED = 10516,
    INVOICES_FIRMCHECK = 10517,
    INVOICES_CONTACT = 10518,
    INVOICES_CONTACT_COUNTRY = 10519,
    INVOICES_EMAIL_HEADER = 10520,
    INVOICES_EMAIL_MESSAGES = 10521,
    INVOICES_WORKFLOWMESSAGE = 10522,
    INVOICES_EMAILCONFIRMATION = 10523,
    INVOICES_MESSGE = 10524,
    INVOICE_CONFIRM = 10525,
}

export enum EntityType {
    Firm = 1,
    ParentEntity = 2,
    AuditingFirm = 3,
    HomeStateRegulator = 5,
    CorporateController = 6,
    SigShareholder = 7,
    UBO_Corporate = 8,
    UBO_Individual = 9,
    Head_Office = 10,
    IndividualController = 11
}

export enum FrimsObject {
    MainMenu = 0,
    OperationMenu = 40,
    FrimsMenu = 80,
    Breach = 400,
    BreachHistory = 401,
    BreachStatus = 402,
    Waiver = 440,
    WaiverHistory = 441,
    WaiverStatus = 442,
    FirmsReportLog = 480,
    Firm = 520,
    Scope = 524,
    Tasks = 560,
    LogForms = 600,
    Ais = 700,
    Invoices = 750,
    CoreDetail = 521,
    ParentEntity = 522,
    Contatcs = 523,
    Controller = 525,
    RegisteredFunds = 526,
    Auditor = 527,
    CRO = 900,
    Supervision = 1000,
    Planning = 1001,
    RiskAssememnt = 1002,
    ReportingSchedule = 1004,
    ReturnsReview = 1005,
    PrudAnanlysis = 1006,
    AssignRoles = 1007,
    RMP = 1015,
    IndividualMenu = 90,
    AIDocs = 701,
    AIAssessment = 702,
    AIRecommendation = 703,
    AIMeetingNotes = 704,
    IndApplications = 705,
    IndPersonalInfo = 706,
    IndCredential = 707,
    IndFunctions = 708,
    IndFP = 709,
    IndOpenItems = 710,
    IndForumAgenda = 711,
    IndSLC = 712,
    Individual = 713,
    AppExtReferences = 1110,
    AIReview = 714,
    FSReporting = 1016,
    ALL = 9999,

    //Added By Suhail on 18-Mar-2011
    ReportingScheduleItem = 1026,
    LateAdminFee = 1027,
    PriorPostition = 715,
    AINOC = 717,
    AINOCRecommendation = 718,
    AIStatusChange = 719,
    GenralSubmission = 100,
    AINOCInternalDocs = 720,


    RptSchItemXBRL = 601, // By IRIS Report Schedule
    RptSchItemNonXBRL = 602, // By IRIS Report Schedule
    SupervisionJournal = 529,
    Regulators = 528,
    Notices = 800,
    NoticesResponse = 801,
    FIRMS_LN_Integration = 2004,
    Enforcement = 530,
    ReportValidation = 1060


}
export enum BreachStatus {
    PassedToLrc = 3,
    Closed = 5,
}
export enum CRORegisterReports {
    ENTER_DATE = 3600,
    INVALID_DATE = 3601,
    SELECT_REPORT_TYPE = 3602,
    SELECT_CRO_REPORT_TYPE = 3603,
    REPORT_MAIN_HEADER = 3604

}

export enum ObjectOpType {
    Create = 40,
    Edit = 41,
    Delete = 42,
    List = 43,
    View = 44,
    Search = 45,
    Save = 46,
    Cancel = 47,
    StartWF = 48,
    Review = 49,
    CancelWF = 50,
    Revise = 51,
    Print = 52,
    ListView = 100
}

export enum DocumentType {
    Q01 = 1,
    Q02 = 2,
    Q03 = 3,
    Q04 = 4,
    Q11 = 5,
    Q12 = 6,
    Q13 = 7,
    Q16 = 8,
    Q100 = 10,
    Q200 = 11,
    Q300 = 12,
    CRO1 = 13,
    CRO2 = 14,
    CRO3 = 15,
    CRO4 = 16,
    QO5 = 17,
    Q06 = 18,
    MLRO = 100,
    CRA = 101,
    RFRA = 102,
    RFRB = 103,
    AFSR = 104,
    SSBR = 105,
    RA = 106,
    WN = 200,
    WS = 201,
    AI = 202,
    Q21 = 39,
    Q23 = 45,
    MRLRORes = 38,
    Q19 = 32,
    Q07 = 19,
}

export enum MessagesLogForm {

    SELECT_FIRM = 1100,
    SELECT_FORMTYPE = 1101,
    SELECT_LOGGEDBY = 1102,
    ENTER_LOGGEDDATE = 1103,
    SELECT_RECEIVEDBY = 1104,
    ENTER_RECIEVEDDATE = 1105,
    SELECT_RECIEPTMETHOD = 1106,
    SELECT_RAAFFILIATES = 1107,
    SELECT_RECIPIENTS = 1108,
    DOCTYPE_UPLOADED_SUCCESSFULLY = 1109,
    DOCSUBTYPE_UPLOADED_SUCCESSFULLY = 1110,
    SELECT_DOCUMENT = 1111,
    IMPERSONATION_FAILED = 1112,
    DOCUMENT_DETAILS_SAVED_SUCCESSFULLY = 1113,
    DOCUMENT_DETAILS_SAVED_SUCCESSFULLY_WITN_EMAIL = 1114,
    FRIMS_UPLOADDOCUMENT = 1115,
    FRIMS_EDITDOCUMENT = 1116,
    SELECT_ATTACHMENTS = 1117,
    RESEND_EMAIL = 1118,
    INVALID_EMAIL_CC = 1119,
    INVALID_EMAIL_TO = 1120,
    ENTER_OTHER_FIRM = 1121,
    NO_ATTACHMENTS = 1122,
    ENTER_SEND_DATE = 1123,
    ERROR_UPLOADING_FILE = 1124,
    ENTER_REQUIREDFIELD_PRIORSAVING = 1125,
    NOT_SHAREPOINT_FILENAME_FRIENDLY = 1126,
    ENTER_EMAIL_SUBJECT = 1127,
    ENTER_EMAIL_BODY = 1128,
    DOCSUBTYPE_EDITED_SUCCESSFULLY = 1129,
    UPLOAD_DOCUMENT = 1130,
    DOCTYPE_SAVED_SUCCESSFULLY = 1131,
    LOGFORMDATAUPLOAD = 1132,
    SELECT_ATTACHMENT_FILE = 1133,
    CANCEL_CHANGE_CONFIRMATION = 1134,


    // Document Selection user control messages.
    NO_RELEVANT_DOCUMENT_FOUND = 1191,

    //Added By Abrar on 14 Dec to Add QFCA and CRO users Email Address
    QFCA_USERS_EmAIL = 1192,
    CRO_USERS_EmAIL = 1193,
    FILE_EXIST_ERROR = 1194,

}

export enum ReportingScheduleMessages {
    REPORTSNOTSCHEDULE_GENERATEPREVIOUSREPORT_SCHEDULEPREVIOUESSCHEDULE = 12000,
    ADD_REPORTLIST = 12001,
    CORRECT_REPORTLIST = 12002,
    REPORTINGPERIODCHANGED_CLICKGENERATEREPORT = 12003,
    SELECT_REPORTTYPE = 12004,
    ENTER_DUEDATE = 12005,
    SELECT_NOTREQUIREDREASON = 12006,
    REPORTINGSCHEDULE_SAVEDSUCCESSFULLY = 12007,
    RETURNREVIEWREFERENCE_CANTDELETEITEM = 12008,
    ENTER_REPORTINPERIODFROM = 12009,
    ENTER_REPORTINPERIODTO = 12010,
    FINANCIALREPORTINGFROM_CANTEQUALORLATER_FINANCIALREPORTINGTODATE = 12011,
    FIRMLICENSEDAUTHORISEDDATE = 12012,
    CORRECTREPORTINGSPAN_NOTMORETHANYEAR = 12013,
    REPORTINGSCHEDULECREATED_ENTERFINANCIALREPORTINGFROMLATERDATE = 12014,
    REPORTINGSCHEDULECREATED_ENTERFINANCIALREPORTINGTOEARLIERDATE = 12015,
    SELECTRECORD_EDIT = 12016,
    SELECTRECORD_DELETE = 12017,
    REPORTINGSCHEDULE_DELETEDSUCCESSFULLY = 12018,
    DOCUMENTLINKED_CANTDELETE = 12019,
    SCHEDULEITEMREFERENCED_CANTDELETE = 12020,
    REPORTSNOTSCHEDULEDFORONEYEAREARLIER = 12021,
    FINANCIALPERIODMONTHISDIFFERENT = 12022,
    REPORTINGSCHEDULECANTBECREATED_FIRMSTATUS = 12023,
    SELECT_REPORTINGSCHEDULE = 12024,
    REPORTING_SCH_TEXT = 12025,
    FINANCIALYEAREND_NOTSETFROMCRO = 12026,
    SELECTRECORD_PRINT = 12027,
    RPTSCH_PUBLISHED_SUCCESSFULLY = 12028,
    RPTSCH_SIGNOFF_STARTED = 12029,
    RPTSCH_PUBLISH_WARNINGMSG = 12030,
    SELECT_RPTSCHITEM_PUBLISH = 12031,
    REPORTING_SCHEDULE_REFERENCED = 12032,
    DONOTCHANGED_REPORTTYPE = 12033,
    REPORTINGSCHEDULEGENERATED_FINANCIALPERIOD = 12034,
    SAVEREPORTINGSCHEDULE_PRIORPRINTING = 12035,

    ENTER_REPORTNAME = 12036,
    SELECT_REPORTSUBMISSIONTYPE = 12037,
    REPORTINGSTARTDATE_FIRSTDAY = 12038,
    ENTER_VALIDREPORTINGSTARTDATE = 12039,
    REPORTINGENDDATE_LASTDAY = 12040,
    ENTER_VALIDREPORTINGENDDATE = 12041,
    SELECT_REPORTINGPERIODTYPE = 12042,
    REPORTINGDATESINVALIDFORSELECTEDFREQUENCY = 12043,
    CHECK_ADDITIONALSHEETS = 12044,
    DUPLICATEREPORTSCHEDULEITEM = 12045,
    DUPLICATEREPORTSCHEDULEITEMSPRESENTONPAGE = 12046,
    DUEDATE_GREATERTHAN_TODATE = 12047,

    WARNINGLINK = 786,
    XBRLService = 11786,
    FILEATTACHED = 12048,
    EFFECTIVEREPORTTYPEDATE = 12050,
    ADDITIONAL_SHEETS_ERROR_MSG = 12056,
    ALLITEM_PUBLISHED = 12057
}

export enum MessagesWaiverList {
    SELECT_WAIVER = 800,
    FIRMEXIST = 801,
    WAIVEREDIT = 802,
    WAIVERNOTFOUND = 803
}

export enum LogFormRecieptMethods {
    Fax = 1,
    Email = 2,
    Mail = 3,
    InternalDocument = 4
}

export enum DocType {
    Waiver = 200,
    Breaches = 201,
    AIs = 202,
    AINOC = 43,
    JournalAttachment = 204,
    EnforcementAttachment = 207,
    RegisteredFund = 208,
    SCOPE = 209,
    FIRM_DOCS = 210
}

export enum FunctionType {
    IndividualController = 11,
    Director = 12,
    Secretary = 13,
    PrincipalRepresentative = 14,
    DirectorMember_NonQFC = 15,
    SEF = 1,
    MLRO = 7,
    CustomerFacing = 10,
    SigShareholder = 19,
    UBO_IndividualController = 25
}
export enum DocType_DocCategory {
    LogForm = 1,
    RptSchedule = 4,
    CRORptSchedule = 5,
    PrudReturn = 6,
    AMLMLROReports = 7,
    XBRLTYPES = 10
}
export enum ReturnReviewMessages {
    SELECTRPT_REVIEW = 9100,
    RPT_REVIEWNOTFOUND = 9101,
    UNABLE_TO_DELETE = 9102,
    CANCEL_RPTREVIEW = 9103,
    RPT_REVIEW_UPDATED_SUCCESSFULLY = 9104,
    RPT_REVIEW_ISSUE = 9105,
    RPT_VALID_DATE = 9106,
    RPT_REVIEW_UPDATESECTION = 706,

    RPT_REVIEW_SAVED_SUCCESSFULLY = 9107,
    SELECT_REPORTRECEIVED = 9108,
    ENTER_PERIODFROM = 9109,
    ENTER_PERIODTO = 9110,
    RETURNREVIEW_SAVE_ERROR = 726,
    CANCEL_RETURNREVIEW_CONFIRM = 1021,
    SELECT_REPORT_TYPES = 9111,

    SELECTED_DUPLICATE_REPORT = 9112,
    SOME_CONFIGENTRY_10 = 9113,
    SOME_CONFIGENTRY_15 = 9114,
    START_WORKFLOW_WITHWARNING = 9115,

    RPTSCHITEM_ALLOWRESUBMIT_WARNING = 9116,
    VALID_RESOLUTION = 9117,
    CORRECT_ACTIONITEM = 9118,
    ENTER_RECIPIENT = 9119,
    ENTER_SUBJECT = 9120,
    ENTER_EMAILBODY = 9121,
    SAVEREPORTREVIEW_BEFORE_PUBLISHINGCOMMENTS = 9122,
    REVIEWCOMMENTSPUBLISH_CANNOTDELETE = 9123,
    ENTER_ITEMDESC = 9124,
    METRAILYCOMPLETECHEKC = 9125,
    LATEFEEIMPOSED_MSG = 9126,
    LATE_FEE_ERROR_MSG = 9127,
    LATE_FEELIST_SELECT = 9128,
    LATE_FEEEIMPOSED = 9129,
    LATE_FEEFORMULA = 9130,
    LATEFEE_IMPOSED = 9131,
    LATEFEE_IMPOSEDACTION = 9132,
    LATEFEE_IMPOSEDACTIONEDITMSG = 9133,
    LATEFEE_CANCELTMSG = 9134,
    MCC_RR_FLAG = 9135,
    NOT_AUTHORIZED_TO_EDIT_MLRO_REPORTS = 1514,
    EXPLANATION_PENDING_WARNINGS = 12049,
    NO_DOCUMENT_SELECTED = 12052
}

export enum FirmRptBasisTypes {
    Solo = 1,
    Consolidated = 2
}

export enum SupervisionData_Messages {
    SUPERVISION_DATA_SAVED_SUCCESSFULLY = 8600,
    INVALID_NO_OF_STAFF = 8601,
    INVALID_TOTAL_STAFF = 8602,
    ENTER_OPERATIONAL_DATE = 8603,
    INVALID_OPERATIONAL_DATE = 8604,
    INVALID_EFFECTIVE_DATE = 8605,
    ENTER_EFFECTIVE_DATE = 8606,
    SUPERVISION_SAVE_ERROR = 8607,

    NO_OF_STAFF_SHOULD_BE_LESS_THAN_OR_EQUAL_TOTAL_STAFF = 8608,
    NOTES_OUT_OF_LIMIT = 8609,
    SELECT_OPERATIONAL_STATUS = 8610
}
export enum RegisteredFund_Messages {
    RegisteredFund_Saved_SUCCESSFULLY = 18042,
    Error_deleting_RegisteredFund = 18045,
}

export enum ResponseTypes {
    Yes_No_NotApplicable = 1,
    Date = 2,
    Number = 3,
    List_of_values_Single_Response = 4,
    List_of_values_Multiple_Response = 5,
    Explanation = 6,
}
export enum FileType {
    Instance = 1,
    HTML = 2,
    Excel_Attachment = 3
}

export enum MessageLogFormReport {
    SELECT_FROM_DATE = 1300,
    SELECT_TO_DATE = 1301,
    INVALID_DATES = 1302
}

export enum GenerateReportType {
    New = 1,
    FromPrevious = 2
}

export enum CROMessages {
    ENTER_VALIDCROAPPLDATE = 3200,
    ENTER_VALIDCROAPPLSTATUSDATE = 3201,
    CROAPPLSTATUSDATE_EXCEEDS_CROAPPLDATE = 3202,

    SELECT_SHAREHOLDERTYPE = 3203,

    DUPLICATE_AUDITOR = 3204,
    ENTER_VALIDAUDITORNAME = 3205,

    SELECT_DSOFUNCTIONTYPE = 3206,

    ENTER_VALIDAUTHSHARES = 3207,
    ENTER_VALIDISSUEDSHARES = 3208,
    ISSUEDSHARES_EXCEEDS_AUTHSHARES = 3209,
    ENTER_VALIDSHARENOMINALVALUE = 3210,

    SELECT_VALIDAUDITOR = 3211,
    VALID_ONESECRETARY = 3212,

    ENTER_VALIDPERCENTAGE = 3213,
    ENTER_VALIDNUMOFSHARES = 3214,
    ENTER_CORPORATESHAREHOLDERNAME = 3215,

    SHARENOMINALVALUE_PRECINVALID = 3216,

    DSO_INVALIDDATEFROM = 3217,
    TOTAL_PCTOFSHARES_EXCEEDS_100 = 3218,

    ENTER_VALIDEFFECTIVEDATE = 3219,

    PROVIDE_MINIMUM_INFORMATION = 3220,
    FIRM_NOTAUDITOR_WARNING = 3221,

    ENTER_VALIDCESSATIONDATE = 3222,
    ENTER_FIRSTNAME = 3223,

    ENTER_VALIDDATEFROM = 3224,
    ENTER_VALIDDATETO = 3225,
    SELECT_RECORDTODELETE = 3226,

    SHAREHOLDER_DELETED = 3231,
    PERSONNEL_DELETED = 3232,

    DSO_INVALIDSECRETARYPERIOD = 3233,
    SELECT_SHARECLASS = 3234,
    DUPLICATE_SHARECLASSTYPES = 3235,
    DUPLICATE_CONTACTWITHFUNCTIONTYPE = 3236,

    SAVED_CRODATATAB = 3237,
    SAVED_PERSONNELTAB = 3238,
    SAVED_SHAREHOLDERSTAB = 3239,
    SAVED_DOCUMENTSTAB = 3240,

    SAVED_WAIVERSTAB = 3241,
    INVALID_WAIVERNUMBER = 3242,
    ENTER_VALIDWAIVEREFFECTIVEDATE = 3243,
    ENTER_VALIDWAIVEREXPIRATIONDATE = 3244,
    SELECT_WAIVERAPPLIESTO = 3245,
    ENTER_EXPLAINOTHER = 3246,
    ENTER_VALIDWAIVERNEWDUEDATE = 3247,
    WAIVERNUMBER_EXISTS = 3248,

    ENTER_WAIVEREFFECTIVEDATE = 3249,
    ENTER_WAIVEREXPIRATIONDATE = 3250,
    ENTER_WAIVERNEWDUEDATE = 3251,
    ENTER_WAIVERREFRULEBEINGWAIVED = 3252,
    WAIVERFINALIZATION_CONFIRMATION = 3253,
    FIRMCROWAIVER_DELETED = 3254,
    WAIVERFINALIZED = 3255,
    EFFECTIVEDATE_SHOULD_BELESSTHAN_EXPIRATIONDATE = 3256,
    WAIVERNEWDUEDATE_SHOULD_BE_FUTURE_OR_CURRENTDATE = 3257,
    WAIVERNEWDUEDATE_SHOULD_NOTBE_GREATER_THAN_EXPIRATIONDATE = 3258,
    WAIVERNEWDUEDATE_SHOULD_NOTBE_LESS_THAN_EFFECTIVEDATE = 3259,



    SAVED_REPORTINGSCHEDULETAB = 3260,
    EXCEPTION_INSERTING_FORMREFERENCE = 3261,
    ENTER_DUEDATE = 3262,
    ENTER_VALIDDUEDATE = 3263,
    ENTER_FIRMCRO_RPTSCHITEMFROM = 3264,
    ENTER_VALIDFIRMCRO_RPTSCHITEMFROM = 3265,
    ENTER_FIRMCRO_RPTSCHITEMTO = 3266,
    ENTER_VALIDFIRMCRO_RPTSCHITEMTO = 3267,
    RPTSCHITEMFROM_SHOULD_BELESSTHAN_RPTSCHITEMTO = 3268,
    SELECT_NOTREQUIREDREASON = 3269,
    SELECT_REPORTTYPE = 3270,
    ENTER_ALL_REQUIREDFIELDS = 3271,
    ADD_REPORTLIST = 3272,
    CORRECT_REPORTLIST = 3273,
    ENTER_VALIDFIRMCRO_REVIEWSTATUSDATE = 3274,
    ENTER_CROREPORTINPERIODFROM = 3275,
    ENTER_CROREPORTINPERIODTO = 3276,
    CRO_FINANCIALREPORTINGFROM_CANTEQUALORLATER_FINANCIALREPORTINGTODATE = 3277,
    CRO_REPORTINGSPAN_NOTMORETHANYEAR = 3278,
    ENTER_VALIDFIRMCRO_REVISEDDUEDATE = 3279,
    CRO_FINANCIALREPORTINGDATES_NOTAPPLICABLE = 3280,
    NO_CROREPORTS_AVAILABLE = 3281,
    REPORTINGSCHEDULECREATED_ENTERREPORTINGFROMLATERDATE = 3282,
    REPORTINGSCHEDULECREATED_ENTERREPORTINGTOEARLIERDATE = 3283,
    REPORTINGPERIODCHANGED_CLICKGENERATEREPORT = 3284,
    CROREPORTING_SCH_HEADER = 3285,
    CROREPORTING_SCH_TEXT = 3286,
    NOREPORT_AVAILABLE_TO_PRINT = 3287,
    SCHEDULEITEMS_ARE_REVIEWED = 3289,

    Alert_FirmCRORptSch_Title = 3290,
    Alert_FirmCRORptSch_Message = 3291,
    PLEASE_SELECT_REPORT_TO_PRINT = 3292,
    WAIVER_IS_FINALIZED_AND_CANNOT_BE_DELETED = 3293,
    CRODOCUMENTLINKED_CANTDELETE = 3294,
    FIRMCROREPORTINGSCHEDULE_DELETED = 3295,
    DUEDATE_SHOULDBE_BETWEEN_REPSCHFROM_TODATE = 3296,

    Alert_FirmCROWaiver_Title = 3297,
    Alert_FirmCROWaiver_Message = 3298,

    SAVED_CROPAGE = 3300
}

export enum FirmUserMessages {
    FirmUser_Added = 8200,
    Date_Exception = 8201,
    UserName_Exception = 8202,
    FunctionRole_Exception = 8203,
    FunctionRole_Exist = 8204,
    User_NoActiveAssignment = 8205,
    Firm_NoUser = 8206,
    User_Updated = 8207,
    RAPersonnel_Exception = 8208,
    FirmUser_Updated = 8209,
    FirmUser_Deleted = 8210
}

export enum WorkFlowStatusType {
    InProgress = 1,
    Completed = 2,
    Returned = 3,
    Cancelled = 4,
}

export enum NotificationFlag {
    Notify = 1,
    NotNotify = 0,
}

export enum LateAdminFeeMSG {
    ENTER_JUSTIFICATION = 18000,
    ENTER_IMPOSEDAMOUNT = 18001,
    VALID_IMPOSEDAMOUNT = 18002,
    ENTER_RECOMMENDATION = 18003,
    SAVED_MSG = 18004,
    FINANCE_EMAILSUBJECT = 18005,
    FINANCE_EMAILTITLE = 18006,
    FINANCE_EMAILRESONS = 18007,
    FINANCE_EMAILREASONSDESC = 18008,
    FINANCE_EMAILMSG = 18009,
    FEE_CANCELLATIONREASON = 18011,
    RULES_CALCULATION = 18012
}

export enum AISMessages
{
    FIRSTNAME = 10000,
    SECONDNAME = 10001,
    DATERECIVIED = 10002,
    FUNCTIONS = 10003,
    STATUSOFAPPLICATION = 10004,
    STATUSDATE = 10005,
    AISSAVEERROR = 10006,
    AIINFROMATIONSAVED = 10007,
    AIAPPLICATIOSAVE = 10008,
    AIAPPLICATION_SAVED_ERROR = 10009,
    AIINFORMATION_SAVED_ERROR = 10010,
    AIINFROMATIO_EMAIL = 10011,
    AISNOTEXISTS = 10012,
    AICONTROLLED = 10013,
    AIS_ADDRESS = 10014,
    AI_DELETE = 10015,
    SELECT_AI = 10016,
    AI_APPLICATIOEXIST = 10017,
    AI_DATEOFBIRTH = 10018,
    AI_OTHEREMAIL = 10019,
    AI_CANCEL = 10020,
    AI_DELETE_MSG = 10021,
    ACTIVITY_TYPEID = 10022,
    ACTIONTYPE_FUNCTION = 10023,
    ACTIONTYPEACTIVITY = 10024,
    AIWITHDRAWN = 10025,
    AICHECK = 10026,
    AIADD = 10027,
    AIDELTE = 10028,
    AIDELTEDMESSAGE = 10029,
    AINUMUBEReXISTS = 10030,
    VALIDAINUMBER = 10031,
    AINUMBERNOTPRESENT = 10032,
    AISTRING = 10033,
    CUSTOMFACING = 10034,
    AI_STATUS = 10035,
    AI_SELECT = 10036,
    AIINAPPLICATION_SELECT = 10037,
    AI_ALIASE = 10038,
    AI_COUNTRY = 10039,
    UNABLE_TO_DELETE = 9102,
    AI_FROMDATE = 10040,
    AI_TODATE = 10041,
    AI_DATEVALID = 10042,
    AI_VALIDMONTH = 10043,
    AI_CREDENTAILSAVE = 10044,
    AI_FUNCTIONSSAVE = 10045,
    AI_RECOMMENDATION_UPDATED_SUCCESSFULLY = 10046,
    AI_RECOMMENDATION_SAVED_SUCCESSFULLY = 10047,
    AI_ASSESSMENT_UPDATED_SUCCESSFULLY = 10048,
    AI_ASSESSMENT_SAVED_SUCCESSFULLY = 10049,
    AI_RECOMMENDATION_WF_SELECT_ONETASK = 10050,
    AI_RECOMMENDATION_WF_PREVS_TASK_NOT_STARTED = 10051,
    AI_RECOMMENDATION_PREV_WF_NOTCOMPLETED = 10052,
    AI_RECOMMENDATION_NOTSTART_AML_LEAD_REVIEW = 10053,
    AI_RECOMMENDATION_APPLIED_FOR_MLRO = 10054,
    AI_ASSESSMENT_TEXT_PLEASE_ENTER = 10055,
    AI_ASSESSMENT_TEXT_DETAIL = 10056,
    AI_ASSESSMENT_PLEASE_ENTER_OTHERDESCRIPTION = 10057,
    AI_ASSESSMENT_FINANCIAL_SOUNDNESS_ISSUE = 10058,
    AI_ASSESSMENT_FITNESS_ISSUE = 10059,
    AI_ASSESSMENT_HONESTY = 10060,
    AI_ASSESSMENT_RESIDENCY_NOTE = 10061,
    AI_ASSESSMENT_WAIVER_NOTE = 10062,
    AI_ASSESSMENT_NO_RECORD_FOUND = 10063,
    AI_OPENITEM_ITEM_TYPE = 10064,
    AI_OPENITEM_ITEM_DESCRIPTION = 10065,
    AI_OPENITEM_ITEM_STATUS = 10066,
    AI_OPENITEM_RESOLVE_DATE = 10067,
    AI_OPENITEM_VALID_DATE = 10068,
    AI_OPENITEM_RESOLVE_DATE_NOT_GREATER_TODAY = 10069,
    AI_OPENITEM_MANNER_ADDRESSED = 10070,
    AI_OPENITEM_SAVED_SUCCESSFULLY = 10071,
    AI_OPENITEM_SAVEERROR = 10072,
    AI_FANDP_SAVED_SUCCESSFULLY = 10073,
    AI_FANDP_SELECT_YESNO = 10074,
    AI_FANDP_NORECORD_FOUND = 10075,
    AI_RECOMMENDATION_AIFORUM_ENDORSED = 10076,
    AI_RECOMMENDATION_ENTER_ROLES = 10077,
    AI_RECOMMENDATION_ENTER_REASON_FOR_APPLFEEWAIVER = 10078,
    AI_DOC_ERROR = 10079,
    AI_PERSONAL_FIRM = 10080,
    AI_PERSONAL_FORMTYPE = 10081,
    AI_APPLICATIONCOMPLETED = 10082,
    AI_RECOMMENDATION_APPLFEEWAIVER_UNCHECKED = 10083,
    AI_RECOMMENDATION_APPLFEEWAIVER_STARTBIT = 10084,
    AI_DOCS_SAVE_MSG = 10085,
    AI_ASSESSMENT_FUNCTION_ISSUE = 10086,
    AI_DOCS_SAVES = 10087,
    AI_SELECT_FILE = 10088,
    AI_PRPOSEDLOCATION = 10089,
    AI_CRE_EMPLOYERNAME = 10090,
    AI_CRE_EMPLOYEMENTRECORD = 10091,
    AI_CRE_TILLDATE = 10092,
    AI_NRD_LIST = 10093,
    AI_DATATO_GREATER_DATETO = 10094,
    AI_MONTHNAME = 10095,
    AI_CRE_VALID_DATE = 10096,
    AI_GAPS_SEVEN = 10097,
    AI_DATE_OVERLAP = 10098,
    AI_DATE_GREATE_TODATE = 10099,
    AI_CRE_CAREER = 10100,
    AI_CRE_QUAL = 10101,
    AI_CRE_CERT = 10102,
    AI_CRE_OVERSEAS = 10103,
    AI_CRE_GAPMSG = 10104,
    AI_PER_NRDMSG = 10105,
    AI_NUMBER_ENTERD = 10106,
    AI_FUNC_APPROVED_DATE = 10107,
    AI_FUNC_WITHDRAWN_DATE = 10108,
    AI_FUNC_DATA = 10109,
    TXT_MONTHS_MSG = 10110,
    NO_PAYMENT_RECEIVED = 10111,
    AI_PER_POROPSED = 10112,
    AI_DOC_SAVE = 10113,
    AI_REC_PENDING_OPENITEMS = 10114,
    AI_FUNCTIONS_NOTEXISTS=10115,
    AI_GAPES_IN_CAREER =10116,
    AI_EMPLYMENT_RECORD=10117,
    AI_VALIDDATES_EMPLOYE=10118,
    NOT_ASSIGNED = 10119,
    ASS_WFREVISION_MESSAGE = 10120,
    REC_WFREVISION_MESSAGE = 10121,
    COUNTRY_MSG =10122,
    AI_FUNCTION_STATUS =10123,
    AI_OPENITEMS_APPPROCESS =10124,
    AI_OPENITEMS_IMPACTNOTES=10125,
    AI_REVIEW_STRATSIGNOFF=10126,
    AI_REVIEW_CANCELLEDSIGNOFF = 10127,
    AI_REVIEW_TASKNOTCOMPLETED = 10128,
    AI_REVIEW_TASKNOTSTARTED = 10129,
    AI_REVIEW_CONFIRMSTRAT = 10130,
    AI_REVIEW_CONFIRMCANCEL = 10131,
    AI_OPENITEM_RESOLVE_DATE_NOT_GREATER_CRETEDDATE = 10132,
    AI_OPENITEM_CREATEDDATE=10133,
    AI_OPENITEM_CREATED_DATE_NOT_GREATER_TODAY = 10134,
    REVIEW_DETAILS_SAVED_SUCCESSFULLY = 10135,
    AI_RECOMMENDATION_TEXT_MESSAGE_Q03_Q11 = 10136,
    AI_RECOMMENDATION_TEXT_MESSAGE_Q12 = 10137,
    ASS_WFREVISION_MESSAGE_UNCHECKED = 10138,
    REC_WFREVISION_MESSAGE_UNCHECKED = 10139,
    AI_GAP_FLAG_NOTES=10140,
    AI_FAP_CHK_NOTES=10141,
    APPLICATION_ESUBMISSION_NOTCOMPLETED = 10142,
    AI_FORMTYPE_SELECTED=10143,
    AI_SYNC_COMP = 10144,
    AI_SCREENINF_SUCC=10145,
    AI_PHONE =10146, // Added by abrar on 16 jun 2011
    ROLE_EXPREIENCE_GREATER=10147,
    ROLESPECIFICEXPERIENCE=10148,
    TOTALINDUSTRYEXPERIENCE=10149,
    AI_OPENITEMS_ISSUESIDENTIFIEDDATE=10150,
    AI_OPENRITEMS_IMPACT=10151,
    AI_KNOWELDEGE_SAVE=10152,
    AI_PRIORPOSITIONSAVE =10153,
    AI_UNABLETOEDIT = 10163,
    AI_CONDAPPROVALDATE = 10164,
    FUNCTIONWITHDRAWNMESSAGE=10165,
    NATUREOFARRANGEMENT=10166,
    ISORDINERLYRESIDENT=10167,
    ENTERCFEXECRSIED=10168,
    AUTHORISEDSCOPE = 10182,
    BUSSINESSEMAILADDRESS_VALIDATION = 10189,

}